#!/bin/bash

# Source the formatting functions (if applicable)
source "$(dirname "$0")/bash_utilities"

# Function to display help information
show_help() {
  print_title "HELP INFORMATION"
  print_header "Usage: $(basename $0) [OPTIONS]"
  echo "This script organizes files in the current directory and its subdirectories"
  echo "into folders based on their creation date (or modification date if creation"
  echo "date is not available). The files will be moved (default) or copied into"
  echo "directories named by year and month."
  print_header "Options:"
  echo "  $(color_bold_blue '-c')         Copy files instead of moving them."
  echo "  $(color_bold_blue '-h, --help') Display this help message."
  print_header "Examples:"
  echo "  $(color_blue "$(basename "$0") -c /path/to/directory")  Copy files to respective folders."
  echo "  $(color_blue "$(basename "$0") /path/to/directory")     Move files to respective folders."
  exit 0
}


# Function to get the creation date of a file
get_creation_date() {
  # Using stat to get the creation date (birth time) of a file
  # The format %Y-%m-%d will give us the year, month, and day
  stat -c %w "$1" 2>/dev/null | cut -d ' ' -f1
}

# Initialize the copy_files variable
copy_files=false

# Parse command line options
while getopts ":ch-:" opt; do
  case ${opt} in
    c )
      copy_files=true
      ;;
    h )
      show_help
      ;;
    - )
      case "${OPTARG}" in
        help )
          show_help
          ;;
        * )
          color_red "Invalid option: --${OPTARG}"
          show_help
          ;;
      esac
      ;;
    \? )
      color_red "Invalid option: -$OPTARG"
      show_help
      ;;
  esac
done

shift $((OPTIND -1))

# Begin operation
print_title "BEGIN FILE ORGANIZATION"
print_header "Organizing files by creation/modification date into Year/Month folders..."

# Loop through all files in the current directory and its subdirectories
find . -type f | while read -r file; do
  # Get the creation date of the file
  creation_date=$(get_creation_date "$file")

  # If the creation date is empty (e.g., for filesystems that do not support birth time), use the modification date
  if [ -z "$creation_date" ]; then
    creation_date=$(stat -c %y "$file" | cut -d ' ' -f1)
  fi

  # Extract the year and month from the creation date
  year=$(echo "$creation_date" | cut -d '-' -f1)
  month=$(echo "$creation_date" | cut -d '-' -f2)

  # Create the target directory if it does not exist
  target_dir="./$year/$month"
  mkdir -p "$target_dir"

  if [ "$copy_files" == true ]; then
    # Copy the file to the target directory
    cp "$file" "$target_dir"
    echo "Copied: $file to $target_dir"
  else
    # Move the file to the target directory
    mv "$file" "$target_dir"
    echo "Moved: $file to $target_dir"
  fi
done
color_green "Complete!"

# End operation
print_title "FILE ORGANIZATION COMPLETE"
